'''
Routines to generate a LaTeX file with canned text while also inserting
graphs generated from CSP routines.

Mike Markowski
mike.ab3ap@gmail.com
Dec 2021 original
Jun 2026
'''

import numpy as np
import util

class LaTeX:

    def __init__(self, latexFile):
        self.latexFile = latexFile

    def beginning(self):
        self.f = open(self.latexFile, 'w')
        s = \
'''\\documentclass[12pt]{article}
\\usepackage[pdftex]{graphicx}
\\usepackage{color}
\\usepackage{float}
\\usepackage{longtable}
\\usepackage[hidelinks]{hyperref}

\\begin{document}

\\title{Cyclostationary Signal Analysis}
\\author{Computer generated report.}
\\maketitle

\\begin{abstract}
 This report is computer generated by python code written by Mike Markowski,
 mike.ab3ap@gmail.com that implements portions of Chad Spooner's CSP blog at
 cyclostationary.blog.  Please fix or report bugs, enhance, and
 share!
\\end{abstract}
\\newpage
\\tableofcontents
\\listoffigures
\\listoftables
\\newpage
'''
        self.f.write(s)

    def blindScf(self, pngC, pngNc, blindType, maxBlind, thresh):
        b = blindType.upper()
        if b == 'SSCA':
            bLong = 'Strip Spectral Correlation Analyzer'
        else:
            bLong = 'FFT Accumulation Method'
        s = \
'''\\section{%s Blind Analysis}

Blind cyclostationary analysis is performed over the entire RF spectrum of
the recording without knowledge of signals.  It provides an estimate of the
spectral correlation function (SCF) for many spectral and cycle frequencies.
The highest values will be studied in greater detail.  The method used here
is the %s, or %s.

A shortcoming of looking at the SCF is that stronger signals will be
found but not necessarily weak ones.  Spectral coherence, dividing SCFs
by appropriately shifted PSDs, normalizes signals to aid comparison.
However, it can also be useful to see the strongest signals at
a receiver.

The following graphs are relative to the recording's center frequency,
labeled 0~Hz and represent the %d highest spectral coherences that are
greater than a threshold of %.1f.  While spectral coherences are
plotted, they are colored by their associated spectral correlation function
values for added information.

'''
        self.f.write(s % (b, b, bLong, maxBlind, thresh))
        s = \
'''
\\begin{sloppypar}
Learn about the SSCA (Strip Spectral Correlation Analyzer) method at
\\url{https://cyclostationary.blog/2016/03/22/csp-estimators-the-strip-spectral-correlation-analyzer/}
and the FAM (FFT Accumulation Method) method at
\\url{https://cyclostationary.blog/2018/06/01/csp-estimators-the-fft-accumulation-method/}.
\\end{sloppypar}
'''
        self.f.write(s)
        s = \
'''
\\subsection{%s Non-conjugate Spectral Coherences}

\\begin{figure}[H]
 \\begin{center}
  \\includegraphics[width=\\textwidth]{%s}
 \\end{center}
 \\caption{%s non-conjugate results.}
\\end{figure}
'''
        self.f.write(s % (b, pngNc, b))
        s = \
'''
\\subsection{%s Conjugate Spectral Coherences}

\\begin{figure}[H]
 \\begin{center}
  \\includegraphics[width=\\textwidth]{%s}
 \\end{center}
 \\caption{%s conjugate results.}
\\end{figure}
'''
        self.f.write(s % (b, pngC, b))

    def cycles(self, pngCyclesC, pngCyclesN,
        alphasC, sC, alphasN, sN, fc_Hz=0, fs_Hz=1):

        s = \
'''\\section{Cycle Frequencies}
From blind analysis results, cycle frequencies with the largest SCFs will be
studied in more detail.  These strongest describe important properties of
the signal, like symbol rate, sub-carrier spacing, pilot tones, cyclic
prefix duration, and others.  After being ranked and retrieved from blind
analysis results, the cycle frequencies and SCF peak values for
non-conjugate and conjugate are plotted.
'''
        self.f.write(s)

        #
        #   N o n - c o n j u g a t e
        #

        s = \
'''
\\subsection{Non-conjugate}
\\begin{figure}[H]
 \\begin{center}
  \\includegraphics[width=\\textwidth]{%s}
 \\end{center}
 \\caption{Non-conjugate cycle frequencies.}
\\end{figure}
'''
        self.f.write(s % pngCyclesN)

        # Scale x axis (cycle freqs).
        _, xPwr10, _ = util.engNot(fs_Hz)
        xPre = util.siPrefix(xPwr10)
        ap = (fs_Hz * alphasN) / 10**xPwr10

        # Scale x axis (max SCFs).
        sp = []
        for i in range(alphasN.size):
            sp.append(max(np.abs(sN[i])))
        sp = np.array(sp)
        _, yPwr10, _ = util.engNot(max(sp))
        sp /= 10**yPwr10

        s = \
'''
\\begin{longtable}{|l|l|} \\hline
\\emph{Cycle (%sHz)} & \\emph{SC (x$10^{%d}$)} \\\\ \\hline\\hline
'''
        self.f.write(s % (xPre, yPwr10))

        # Generate lines of cycle frequency table.
        ind = np.argsort(sp)[::-1] # Indices to reverse sort sp array.
        top = 20 # Print top matches.
        for i in range(ap.size):
            self.f.write('%.4f & %.1f \\\\ \\hline\n'
                % (ap[ind[i]], sp[ind[i]]))
            top -= 1
            if top == 0:
                break

        s = \
'''
\\caption{Table of non-conjugate cycle frequencies.}
\\end{longtable}
'''
        self.f.write(s)

        #
        #   C o n j u g a t e
        #

        s = \
'''
\\subsection{Conjugate}

\\begin{figure}[H]
 \\begin{center}
  \\includegraphics[width=\\textwidth]{%s}
 \\end{center}
 \\caption{Conjugate cycle frequencies.}
\\end{figure}
'''
        self.f.write(s % pngCyclesC)

        # Scale x axis (cycle freqs).
        _, xPwr10, _ = util.engNot(fs_Hz)
        xPre = util.siPrefix(xPwr10)
        ap = (fs_Hz * alphasC) / 10**xPwr10

        # Scale x axis (max SCFs).
        sp = []
        for i in range(alphasC.size):
            sp.append(max(np.abs(sC[i])))
        sp = np.array(sp)
        _, yPwr10, _ = util.engNot(max(sp))
        sp /= 10**yPwr10

        s = \
'''
\\begin{longtable}{|l|l|} \\hline
\\emph{Cycle (%sHz)} & \\emph{SC (x$10^{%d}$)} \\\\ \\hline\\hline
'''
        self.f.write(s % (xPre, yPwr10))

        # Generate lines of cycle frequency table.
        ind = np.argsort(sp)[::-1] # Indices to reverse sort sp array.
        top = 20 # Print top matches.
        for i in range(ap.size):
            self.f.write('%.4f & %.1f \\\\ \\hline\n'
                % (ap[ind[i]], sp[ind[i]]))
            top -= 1
            if top == 0:
                break

        s = \
'''
\\caption{Table of conjugate cycle frequencies.}
\\end{longtable}
'''
        self.f.write(s)

    def ending(self, cpu_s):
        mins, sec = divmod(cpu_s, 60)
        hr, mins = divmod(mins, 60)
        elap = ''
        elap += '%d hr, ' % int(hr) if hr > 0 else elap
        elap += '%d min, ' % int(mins) if mins > 0 else elap
        elap += '%.1f sec' % sec

        s = \
'''\\newpage
\\section{Document Information}

Cyclostationary analysis and data plotting presented in this document
were created by a program written in python and required %s of
processing time.  The program generated the \\LaTeX\\ input document collecting
results and providing basic descriptions.  This can be used as a starting
point for an in-depth analysis, for example, explaining the reasons for
observed cycle frequencies.
\\end{document}
'''
        self.f.write(s % elap)
        self.f.close()

    def intro(self, sigFile, sigTime, sigFreq, cmd):
        s = \
'''\\section{Introduction}
This report presents an automated cyclostationary analysis of the signal
recorded in the file \\verb|%s|.  The results and the report
itself can be recreated with the command:
\\\\~\\\\
\\indent \\verb|%s|
\\\\~\\\\
There are two major steps in cyclostationary analysis:
\\begin{enumerate}
\\item Blind analysis, where the spectrum of interest is studied to
efficiently find significant spectral and cycle frequencies.  Spectral
frequencies are those that a signal is composed of.  Cyclic frequencies
represent repeating features of a signal like symbol rate, chip rate,
and so on, and are useful for both detecting and classifying signals.

\\item Spectral Correlation Function (SCF), where only the strongest signals
found in the blind study are studied in greater detail.
\\end{enumerate}

\\begin{sloppypar}
The mathematics underlying the analysis can be found at the website
\\url{https://cyclostationary.blog} by Dr.\\ Chad Spooner.
Importantly, when considering real world signals rather than textbook perfect
ones, on
the page \\\\
\\url{https://cyclostationary.blog/2016/01/19/textbook-signals/}
he says, ``Transmitter impairments include phase
noise, carrier-frequency drift, symbol-clock jitter, and gain/phase mismatch.
These effects typically weaken the cyclostationarity of the signal, but do
not typically introduce new periods of cyclostationarity (new cycle
frequencies).''  Visit the web page for more detail.
\\end{sloppypar}

The power spectral density of the signal analyzed in this report is
displayed in Figure~\\ref{fig:sigFreq}.
\\begin{figure}[H]
 \\begin{center}
  \\includegraphics[width=\\textwidth]{%s}
 \\end{center}
 \\caption{Power spectrum of signal analyzed.}
 \\label{fig:sigFreq}
\\end{figure}
'''
        self.f.write(s % (sigFile, cmd, sigFreq))

    def scf(self, pngScfC, pngScfN, scfType, thresh, win, n):

        st = scfType.upper()
        stLong = 'Time' if st == 'TSM' else 'Frequency'
        stLong += ' Smoothing Method'

        s = \
'''\\section{Spectral Correlation Function, %s}

As previously described, the spectral correlation function (SCF) is
calculated for a small number of cycle frequencies discovered by a blind
search.  The SCF curves presented in the following graphs are chosen as
described in Section~\\ref{sec:sc}.  The difference is that SCFs are plotted,
not spectral coherences, and only the top %d are presented.  SCFs are
calculated using the %s with '''
        self.f.write(s % (stLong, n, stLong))
        if st == 'TSM':
            s = 'an analysis block size of %d samples.'
        else:
            s = 'a smoothing window %d samples wide.'
        self.f.write(s % win)

        s = \
'''
\\begin{sloppypar}
Both types of CSP estimators are described at
\\url{https://cyclostationary.blog/2015/11/20/csp-estimators-the-frequency-smoothing-method/},
the time smoothing method, and also at
\\url{https://cyclostationary.blog/2016/03/22/csp-estimators-the-strip-spectral-correlation-analyzer/},
the frequency smoothing method.
\\end{sloppypar}
'''
        self.f.write(s)
        s = \
'''
\\subsection{Non-conjugate}

\\begin{figure}[H]
 \\begin{center}
  \\includegraphics[width=\\textwidth]{%s}
 \\end{center}
 \\caption{Non-conjugate SCF.}
\\end{figure}
'''
        self.f.write(s % pngScfN)
        s = \
'''
\\subsection{Conjugate}

\\begin{figure}[H]
 \\begin{center}
  \\includegraphics[width=\\textwidth]{%s}
 \\end{center}
 \\caption{Conjugate SCFs for top cyclic frequencies, $\\alpha$.}
\\end{figure}
'''
        self.f.write(s % pngScfC)

    def slices(self, pngScfC, pngScfN, scfType, thresh, win, n):

        st = scfType.upper()
        stLong = 'Time' if st == 'TSM' else 'Frequency'
        stLong += ' Smoothing Method'

        s = \
'''\\section{Spectral Coherence}
\\label{sec:sc}

After the blind detection presented above, spectral coherence (SC) values
below a threshold of %.1f are dropped and the remaining are ranked by
strongest SCF.  The following graphs show spectral coherence curves for
the top %d cycle frequencies from the ranking.  The SCFs are calculated with
the %s, which is divided by the PSD (Power Spectral Density) to obtain the
spectral coherence curves.  The SCF uses absolute signal strength and the SC
is used for normalized comparison.  Finally, those %d curves those are plotted
in the graphs in this section.

As before, spectral frequencies are relative to center frequency and labeled
zero.  Symmetric values about the vertical axis are ignored, as is the PSD
($\\alpha = 0$) in the non-conjugate case.

\\begin{sloppypar}
The spectral coherence function is described in detail at 
\\url{https://cyclostationary.blog/2016/01/08/the-spectral-coherence-function/}.
\\end{sloppypar}
'''
        self.f.write(s % (thresh, n, stLong, n))
        s = \
'''
\\subsection{Non-conjugate}

\\begin{figure}[H]
 \\begin{center}
  \\includegraphics[width=\\textwidth]{%s}
 \\end{center}
 \\caption{Top %d non-conjugate SC curves.}
\\end{figure}
'''
        self.f.write(s % (pngScfN, n))

        s = \
'''
\\subsection{Conjugate}

\\begin{figure}[H]
 \\begin{center}
  \\includegraphics[width=\\textwidth]{%s}
 \\end{center}
 \\caption{Top %d conjugate SC curves.}
\\end{figure}
'''
        self.f.write(s % (pngScfC, n))

